// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdgakosznmfoyvwtlwcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZ2Frb3N6bm1mb3l2d3Rsd2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNTExNjEsImV4cCI6MjA4NjcyNzE2MX0.pYF3mFMkNTjNCQvb9-pGXSGonxcfrGbMwKoSomy-93U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});